version: '3.2'

services:
  astro-db-mssql:
    image: astro-db-mssql
    container_name: astro-db-mssql
    build: ./db-mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "My_Password1"
    volumes:
      - ./mssql-server-data:/var/opt/mssql
    networks:
      - astro
  
  astro-catalog-server:
    image: astro-catalog-server
    container_name: astro-catalog-server
    build: ./catalog-server
    ports:
      - "8081:8080"
    environment:
      - database=jdbc:sqlserver://172.18.0.1:1433
    depends_on:
      - astro-db-mssql
    networks:
      - astro

networks:
  astro:

