version: '3.2'

services:
  astro-db-mssql:
    image: astro-db-mssql
    container_name: astro-db-mssql
    build: ./db-mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "My_Password1"
    volumes:
      - ./mssql-server-data:/var/opt/mssql

